os:
  - linux
  - osx
  - windows
language:
  - cpp
compiler:
  - clang
  - gcc
before_script:
  - cd build
script:
  - cmake --version
  - cmake -S ..
  - cmake --build . --config release
  - echo true | cmake --build . --target run
after_success:
  - if [ $TRAVIS_OS_NAME = windows ]; then
      cmake -E md5sum Release/duke.exe ;
      ls -lh Release ;
    else
      cmake -E md5sum duke ;
      ls -lh ;
    fi
after_failure:
  - ls -lh
