language: cpp
jobs:
  include:
    - os: linux
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      addons: { apt: { packages: ["g++-9"], sources: ["ubuntu-toolchain-r-test"] } }
    - os: osx
      osx_image: xcode11.2
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: windows
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
install:
  - eval "${MATRIX_EVAL}"
before_script:
  - cd build
script:
  - cmake -S ..
  - cmake --build . --config release
  - |
    function run () {
      cmake -S .. -DCMAKE_BUILD_TYPE=Release -DRUN_ARGS="$PWD/$@"
      cmake --build . --config release --target run
    }
  - run ../test/boolean/false.js
  - run ../test/boolean/true.js
  - run ../test/dracula/index.js
  - run ../test/error/index.js
  - run ../test/json/data.json
  - run ../test/json/index.js
  - run ../test/module/index.js
  - run ../test/quicksort/index.js
  - echo "console.log(0)" | run ../test/stdin/index.js
  - echo "console.log(1)" | run ../test/stdin/index.js
after_success:
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = linux ]; then
      cmake -E rename duke duke-linux-x64 ; chmod +x duke-linux-x64 ;
      cmake -E md5sum duke-linux-x64 > duke-linux-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = osx ]; then
      cmake -E rename duke duke-macos-x64 ; chmod +x duke-macos-x64 ;
      cmake -E md5sum duke-macos-x64 > duke-macos-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = windows ]; then
      cmake -E rename Release/duke.exe duke-winnt-x64.exe ;
      cmake -E md5sum duke-winnt-x64.exe > duke-winnt-x64.exe.md5 ;
    fi
  - ls -lh
after_failure:
  - ls -lh
deploy:
  provider: releases
  token:
    secure: $GITHUB_DEPLOY_TOKEN
  file_glob: true
  file:
    - "duke-*-x64*"
  draft: true
  on:
    condition: $GITHUB_DEPLOY
    tags: true
