os:
  - linux
  - osx
  - windows
language:
  - cpp
compiler:
  - clang
  - gcc
before_script:
  - cd build
script:
  - cmake --version
  - cmake -S ..
  - cmake --build . --config release
  - echo true | cmake --build . --target run
after_success:
  - if [ $TRAVIS_COMPILER = gcc ] && [ $TRAVIS_OS_NAME = linux ]; then
      cmake -E rename duke duke-linux-x64 ; chmod +x duke-linux-x64 ;
      cmake -E md5sum duke-linux-x64 > duke-linux-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = gcc ] && [ $TRAVIS_OS_NAME = osx ]; then
      cmake -E rename duke duke-macos-x64 ; chmod +x duke-macos-x64 ;
      cmake -E md5sum duke-macos-x64 > duke-macos-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = gcc ] && [ $TRAVIS_OS_NAME = windows ]; then
      cmake -E rename Release/duke.exe duke-winnt-x64.exe ;
      cmake -E md5sum duke-winnt-x64.exe > duke-winnt-x64.exe.md5 ;
    fi
  - ls -lh
after_failure:
  - ls -lh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_TOKEN
  file_glob: true
  file:
    - "duke-*-x64*"
  skip_cleanup: true
  draft: true
  on:
    condition: $GITHUB_DEPLOY
    tags: true
