language: cpp
matrix:
  include:
    - os: linux
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      addons: { apt: { packages: ["g++-9"], sources: ["ubuntu-toolchain-r-test"] } }
    - os: osx
      osx_image: xcode11.2
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: windows
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
install:
  - eval "${MATRIX_EVAL}"
before_script:
  - cd build
script:
  - cmake -S ..
  - cmake --build . --config release
  - cmake --build . --config release --target run < ../test/boolean/false.js
  - cmake --build . --config release --target run < ../test/boolean/true.js
  - cmake --build . --config release --target run < ../test/module/index.js
  - cmake --build . --config release --target run < ../test/module/module-a.js
  - cmake --build . --config release --target run < ../test/module/module-b.js
  - cmake --build . --config release --target run < ../test/module/module-c.js
  - cmake --build . --config release --target run < ../test/quicksort/index.js
after_success:
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = linux ]; then
      cmake -E rename duke duke-linux-x64 ; chmod +x duke-linux-x64 ;
      cmake -E md5sum duke-linux-x64 > duke-linux-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = osx ]; then
      cmake -E rename duke duke-macos-x64 ; chmod +x duke-macos-x64 ;
      cmake -E md5sum duke-macos-x64 > duke-macos-x64.md5 ;
    fi
  - if [ $TRAVIS_COMPILER = g++ ] && [ $TRAVIS_OS_NAME = windows ]; then
      cmake -E rename Release/duke.exe duke-winnt-x64.exe ;
      cmake -E md5sum duke-winnt-x64.exe > duke-winnt-x64.exe.md5 ;
    fi
  - ls -lh
after_failure:
  - ls -lh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_TOKEN
  file_glob: true
  file:
    - "duke-*-x64*"
  skip_cleanup: true
  draft: true
  on:
    condition: $GITHUB_DEPLOY
    tags: true
